const DEFAULT_API = localStorage.getItem('backyardApiUrl') || '';
const state = { plants: [], filtered: [] };
const els = id => document.getElementById(id);
const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

els('apiUrl').value = DEFAULT_API;
els('saveApi').onclick = () => { localStorage.setItem('backyardApiUrl', els('apiUrl').value.trim()); loadPlants(); };
['search','typeFilter','sunFilter','rabbitFilter','sortBy'].forEach(id=>els(id).addEventListener('input', render));
els('addPlant').onclick = () => openModal({});
els('savePlant').onclick = async ev => { ev.preventDefault(); await savePlant(); };
if(DEFAULT_API) loadPlants(); else loadFallback();

function apiUrl(params={}){ const base=els('apiUrl').value.trim(); const u=new URL(base); Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v)); return u.toString(); }
function jsonp(url){ return new Promise((resolve,reject)=>{ const cb='cb_'+Date.now()+'_'+Math.random().toString(36).slice(2); window[cb]=d=>{delete window[cb]; s.remove(); resolve(d)}; const s=document.createElement('script'); s.src=url+(url.includes('?')?'&':'?')+'callback='+cb; s.onerror=reject; document.body.appendChild(s); }); }
async function loadPlants(){ try{ els('syncStatus').textContent='Loading…'; const data=await jsonp(apiUrl({action:'plants'})); state.plants=data.plants || data || []; els('syncStatus').textContent=`Connected · ${state.plants.length} plants`; hydrateFilters(); render(); }catch(e){ console.error(e); els('syncStatus').textContent='Could not load. Showing demo data.'; loadFallback(); } }
function loadFallback(){ state.plants=[
{name:'Bee Balm',quantity:3,type:'Perennial',sun:'Full sun',water:'Medium',bloom:'June-July',rabbit:'Low/Medium',prune:'Deadhead after bloom; cut back in late winter',fertilize:'Light compost/organic feed in spring',winter:'Dies back; returns from roots',notes:'Can mildew in humidity; wants airflow'},
{name:'Blueberries',quantity:2,type:'Fruit shrub',sun:'Full sun',water:'Medium/high',bloom:'Fruit June-July',rabbit:'High',prune:'Late winter after year 3',fertilize:'Acid-loving fertilizer spring',fruit:'Net before berries turn blue; harvest when fully blue and sweet',winter:'Hardy; protect flowers only from late frost'},
{name:'Serendipity Allium',quantity:4,type:'Perennial',sun:'Full sun',water:'Low/medium',bloom:'Late June-July',rabbit:'Low',prune:'Deadhead or leave seedheads; cut foliage when tired',fertilize:'Minimal',winter:'Dies back or semi-evergreen; hardy'},
{name:'Swamp Sunflower',quantity:3,type:'Perennial',sun:'Full sun',water:'Medium/high',bloom:'Sep-Oct',rabbit:'High',prune:'Chelsea chop May/June optional; cut down winter',fertilize:'Light spring feed',winter:'Dies to ground; hardy',notes:'Rabbits are currently annihilating this.'}
]; hydrateFilters(); render(); }
function val(p, keys){ for(const k of keys){ const found=Object.keys(p).find(x=>norm(x)===norm(k)); if(found && p[found]!==undefined) return p[found]; } return ''; }
function norm(s){ return String(s||'').toLowerCase().replace(/[^a-z0-9]/g,''); }
function hydrateFilters(){ fill('typeFilter',[...new Set(state.plants.map(p=>val(p,['Type','Plant Type'])).filter(Boolean))]); fill('sunFilter',[...new Set(state.plants.map(p=>val(p,['Sun','Sun Exposure'])).filter(Boolean))]); fill('rabbitFilter',[...new Set(state.plants.map(p=>val(p,['Rabbits','Rabbit Risk','Rabbit Resistance'])).filter(Boolean))]); }
function fill(id,arr){ const el=els(id), first=el.options[0].outerHTML; el.innerHTML=first+arr.sort().map(x=>`<option>${escapeHtml(x)}</option>`).join(''); }
function render(){ const q=els('search').value.toLowerCase(), tf=els('typeFilter').value, sf=els('sunFilter').value, rf=els('rabbitFilter').value; let plants=state.plants.filter(p=>JSON.stringify(p).toLowerCase().includes(q)); if(tf) plants=plants.filter(p=>val(p,['Type','Plant Type'])===tf); if(sf) plants=plants.filter(p=>val(p,['Sun','Sun Exposure'])===sf); if(rf) plants=plants.filter(p=>val(p,['Rabbits','Rabbit Risk','Rabbit Resistance'])===rf); const sort=els('sortBy').value; plants.sort((a,b)=>String(val(a,[sort,'Name','Plant'])).localeCompare(String(val(b,[sort,'Name','Plant'])))); state.filtered=plants; renderKpis(plants); renderTasks(plants); renderTimeline(plants); renderCards(plants); }
function renderKpis(plants){ const total=plants.length; const high=plants.filter(p=>/high|favorite|candy/i.test(val(p,['Rabbits','Rabbit Risk','Rabbit Resistance']))).length; const fruit=plants.filter(p=>/fruit|berry|peach|olive|strawberry/i.test(JSON.stringify(p))).length; const summer=plants.filter(p=>/jun|jul|aug|summer/i.test(val(p,['Bloom','Bloom Time','Fruit Window']))).length; els('kpis').innerHTML=[['Plants',total],['Rabbit targets',high],['Fruit/edibles',fruit],['Summer interest',summer]].map(([a,b])=>`<div class="kpi"><span>${a}</span><strong>${b}</strong></div>`).join(''); }
function renderTasks(plants){ const tasks=[]; plants.forEach(p=>{ const name=nameOf(p); const rabbit=val(p,['Rabbits','Rabbit Risk','Rabbit Resistance']); if(/high|favorite|candy/i.test(rabbit)) tasks.push([name,'Protect/check for rabbit damage']); const prune=val(p,['Prune','When to Prune','Pruning']); if(/deadhead|spent/i.test(prune)) tasks.push([name,prune]); const fruit=val(p,['Fruit','Harvest','Fruit / Harvest / Protection']); if(/net|protect|bird|squirrel/i.test(fruit)) tasks.push([name,fruit]); }); els('tasks').innerHTML=(tasks.slice(0,9).map(([n,t])=>`<div class="task"><span class="dot"></span><div><b>${escapeHtml(n)}</b><br>${escapeHtml(t)}</div></div>`).join('') || '<p>No urgent tasks found. Weirdly peaceful.</p>'); }
function renderTimeline(plants){ const byMonth=months.map(m=>plants.filter(p=>new RegExp(m,'i').test(val(p,['Bloom','Bloom Time','Fruit Window','Fruit','Harvest'])))); els('timeline').innerHTML=byMonth.map((arr,i)=>{ const w=Math.min(100,arr.length*18); return `<div><div class="month-row"><b>${months[i]}</b><div class="barwrap"><div class="bar" style="width:${w}%"></div></div></div><div class="barlabel">${arr.slice(0,4).map(nameOf).join(', ')}</div></div>` }).join(''); }
function renderCards(plants){ els('plantGrid').innerHTML=plants.map((p,i)=>{ const rabbit=val(p,['Rabbits','Rabbit Risk','Rabbit Resistance']); const cls=/high|favorite|candy/i.test(rabbit)?'rabbit-high':/low|resistant/i.test(rabbit)?'rabbit-low':''; return `<article class="plant-card ${cls}"><h3>${escapeHtml(nameOf(p))}</h3><div class="badges"><span class="badge">${escapeHtml(val(p,['Type','Plant Type'])||'Plant')}</span><span class="badge">Qty ${escapeHtml(val(p,['Quantity','Qty'])||'')}</span><span class="badge ${/high/i.test(rabbit)?'warn':''}">🐇 ${escapeHtml(rabbit||'')}</span></div><div class="details"><div><b>Sun:</b> ${escapeHtml(val(p,['Sun','Sun Exposure']))}</div><div><b>Water:</b> ${escapeHtml(val(p,['Water']))}</div><div><b>Bloom/Fruit:</b> ${escapeHtml(val(p,['Bloom','Bloom Time','Fruit Window']))}</div><div><b>Prune:</b> ${escapeHtml(val(p,['Prune','When to Prune','Pruning']))}</div><div><b>Fertilize:</b> ${escapeHtml(val(p,['Fertilize','Fertilizer']))}</div><div><b>Winter:</b> ${escapeHtml(val(p,['Winter','Freeze','Winter / Freeze Notes']))}</div></div><div class="notes">${escapeHtml(val(p,['Notes','Care Notes']))}</div><button onclick='openModalByIndex(${i})'>Edit / Notes</button></article>` }).join(''); }
function nameOf(p){ return val(p,['Plant','Name','Plant Name']) || 'Unnamed plant'; }
function openModalByIndex(i){ openModal(state.filtered[i]); }
function openModal(p){ els('rowNumber').value=p.rowNumber||p._row||''; els('plantName').value=nameOf(p); els('quantity').value=val(p,['Quantity','Qty']); els('type').value=val(p,['Type','Plant Type']); els('zone').value=val(p,['Zone','Location']); els('sun').value=val(p,['Sun','Sun Exposure']); els('water').value=val(p,['Water']); els('bloom').value=val(p,['Bloom','Bloom Time','Fruit Window']); els('rabbit').value=val(p,['Rabbits','Rabbit Risk','Rabbit Resistance']); els('prune').value=val(p,['Prune','When to Prune','Pruning']); els('fertilize').value=val(p,['Fertilize','Fertilizer']); els('fruit').value=val(p,['Fruit','Harvest','Fruit / Harvest / Protection']); els('winter').value=val(p,['Winter','Freeze','Winter / Freeze Notes']); els('notes').value=val(p,['Notes','Care Notes']); els('plantDialog').showModal(); }
async function savePlant(){ const payload={rowNumber:els('rowNumber').value,Plant:els('plantName').value,Quantity:els('quantity').value,Type:els('type').value,Zone:els('zone').value,Sun:els('sun').value,Water:els('water').value,Bloom:els('bloom').value,'Rabbit Risk':els('rabbit').value,Prune:els('prune').value,Fertilize:els('fertilize').value,Fruit:els('fruit').value,Winter:els('winter').value,Notes:els('notes').value}; try{ await fetch(apiUrl({action:'upsert'}),{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify(payload)}); els('plantDialog').close(); els('syncStatus').textContent='Saved. Reloading…'; setTimeout(loadPlants,1600); }catch(e){ alert('Save sent but browser blocked the response. Reloading.'); setTimeout(loadPlants,1600); } }
function escapeHtml(x){ return String(x??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m])); }
