// Hard-code your Apps Script Web App URL here. It must end in /exec.
const API_URL = 'https://script.google.com/macros/s/AKfycbyI7uiNmZXtMy-pnDo_J_kvEhzIbEkCaguQ2-nqDdIQWRlyWdZE7f8QeRZYKV7GMXJy/exec';

const state = { plants: [], filtered: [] };
const $ = id => document.getElementById(id);
const MONTHS = [
  ['Jan','january'],['Feb','february'],['Mar','march'],['Apr','april'],['May','may'],['Jun','june'],
  ['Jul','july'],['Aug','august'],['Sep','september'],['Oct','october'],['Nov','november'],['Dec','december']
];
const FIELD_ALIASES = {
  Plant:['Plant','Name','Plant Name'], Quantity:['Quantity','Qty'], Type:['Type','Plant Type','Category'], Zone:['Zone','Location','Area'],
  Sun:['Sun','Sun Exposure','Light'], Water:['Water','Water Needs'], Bloom:['Bloom','Bloom Time','Bloom/Fruit','Bloom / Fruit Window','Fruit Window'],
  Rabbit:['Rabbit Risk','Rabbits','Rabbit Resistance','Rabbit'], Prune:['Prune','Pruning','When to Prune'], Fertilize:['Fertilize','Fertilizer','Feeding'],
  Fruit:['Fruit','Harvest','Fruit / Harvest / Protection','Fruit/Harvest'], Winter:['Winter','Freeze','Winter / Freeze Notes','Winter/Freeze'], Notes:['Notes','Care Notes']
};

$('reload').onclick = loadPlants;
$('addPlant').onclick = () => openModal({});
$('savePlant').onclick = async ev => { ev.preventDefault(); await savePlant(); };
['search','typeFilter','sunFilter','rabbitFilter','sortBy'].forEach(id => $(id).addEventListener('input', render));
document.querySelectorAll('.nav').forEach(btn => btn.onclick = () => switchView(btn.dataset.view));
loadPlants();

function switchView(view){ document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view)); document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`)); }
function apiUrl(params={}){ if(!API_URL || API_URL.includes('PASTE_')) throw new Error('Paste your Apps Script URL into API_URL in app.js'); const u=new URL(API_URL); Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v)); return u.toString(); }
function jsonp(url){ return new Promise((resolve,reject)=>{ const cb='backyard_cb_'+Date.now(); window[cb]=d=>{delete window[cb]; script.remove(); resolve(d)}; const script=document.createElement('script'); script.src=url+(url.includes('?')?'&':'?')+'callback='+cb; script.onerror=reject; document.body.appendChild(script); }); }
async function loadPlants(){ try{ $('syncStatus').textContent='Connecting…'; const data=await jsonp(apiUrl({action:'plants'})); state.plants=(data.plants || data || []).map(normalizePlant); $('syncStatus').textContent=`Connected · ${state.plants.length} plants`; hydrateFilters(); render(); }catch(err){ console.error(err); $('syncStatus').textContent='Using demo data. Set API_URL in app.js.'; state.plants=demoPlants().map(normalizePlant); hydrateFilters(); render(); } }
function normalizePlant(p){ return {...p,_name:get(p,'Plant'),_qty:get(p,'Quantity'),_type:get(p,'Type'),_zone:get(p,'Zone'),_sun:get(p,'Sun'),_water:get(p,'Water'),_bloom:get(p,'Bloom'),_rabbit:get(p,'Rabbit'),_prune:get(p,'Prune'),_fert:get(p,'Fertilize'),_fruit:get(p,'Fruit'),_winter:get(p,'Winter'),_notes:get(p,'Notes')}; }
function get(p,key){ for(const k of FIELD_ALIASES[key]||[key]){ const actual=Object.keys(p).find(x=>norm(x)===norm(k)); if(actual && p[actual] != null) return String(p[actual]); } return ''; }
function norm(s){ return String(s||'').toLowerCase().replace(/[^a-z0-9]/g,''); }
function hydrateFilters(){ fill('typeFilter',[...new Set(state.plants.map(p=>p._type).filter(Boolean))]); fill('sunFilter',[...new Set(state.plants.map(p=>p._sun).filter(Boolean))]); fill('rabbitFilter',[...new Set(state.plants.map(p=>p._rabbit).filter(Boolean))]); }
function fill(id, arr){ const el=$(id), first=el.options[0].outerHTML; el.innerHTML=first+arr.sort().map(x=>`<option>${esc(x)}</option>`).join(''); }
function render(){ const q=$('search').value.toLowerCase(); let plants=state.plants.filter(p=>JSON.stringify(p).toLowerCase().includes(q)); if($('typeFilter').value) plants=plants.filter(p=>p._type===$('typeFilter').value); if($('sunFilter').value) plants=plants.filter(p=>p._sun===$('sunFilter').value); if($('rabbitFilter').value) plants=plants.filter(p=>p._rabbit===$('rabbitFilter').value); const sortKey=$('sortBy').value; plants.sort((a,b)=>get(a,sortKey).localeCompare(get(b,sortKey))); state.filtered=plants; renderKpis(plants); renderTasks(plants); renderNow(plants); renderRisk(plants); renderCards(plants); renderCalendar(plants); }
function renderKpis(plants){ const high=plants.filter(isRabbitTarget).length, fruit=plants.filter(isFruit).length, blooms=plants.filter(p=>monthsFor(p).length).length; $('kpis').innerHTML=kpi('Plants',plants.length)+kpi('Rabbit targets',high)+kpi('Fruit/edibles',fruit)+kpi('Calendar items',blooms); }
function kpi(label,value){ return `<div class="kpi"><span>${label}</span><strong>${value}</strong></div>`; }
function renderTasks(plants){ const tasks=[]; plants.forEach(p=>{ if(isRabbitTarget(p)) tasks.push([p._name,'Protect/check for rabbit damage']); if(/deadhead|spent|after bloom/i.test(p._prune)) tasks.push([p._name,p._prune]); if(/net|protect|bird|squirrel|harvest|ripe/i.test(p._fruit)) tasks.push([p._name,p._fruit]); if(/freeze|frost|protect/i.test(p._winter)) tasks.push([p._name,p._winter]); }); const html=tasks.slice(0,18).map(([n,t])=>`<div class="task"><span class="dot"></span><div><b>${esc(n)}</b><br>${esc(t)}</div></div>`).join('') || '<p>No urgent tasks found. Suspiciously peaceful.</p>'; $('tasksPreview').innerHTML=html; $('tasksFull').innerHTML=html; }
function renderNow(plants){ const current=new Date().getMonth(); const arr=plants.filter(p=>monthsFor(p).includes(current)).slice(0,10); $('nowList').innerHTML=arr.map(p=>`<div class="mini-item"><b>${esc(p._name)}</b><br><small>${esc(p._bloom || p._fruit)}</small></div>`).join('') || '<p>Nothing mapped to this month yet.</p>'; }
function renderRisk(plants){ $('riskStrip').innerHTML=plants.filter(isRabbitTarget).slice(0,10).map(p=>`<div class="risk-card"><b>${esc(p._name)}</b><br><small>${esc(p._rabbit || 'Rabbit risk')}</small></div>`).join('') || '<p>No high-risk plants in this filtered view.</p>'; }
function renderCards(plants){ $('plantGrid').innerHTML=plants.map((p,i)=>`<article class="plant-card ${isRabbitTarget(p)?'high':isRabbitSafe(p)?'low':''}"><h3>${esc(p._name)}</h3><div class="badges"><span class="badge">${esc(p._type||'Plant')}</span><span class="badge">Qty ${esc(p._qty||'')}</span><span class="badge ${isRabbitTarget(p)?'warn':''}">🐇 ${esc(p._rabbit||'')}</span></div><div class="facts"><div><b>Sun:</b> ${esc(p._sun)}</div><div><b>Water:</b> ${esc(p._water)}</div><div><b>Bloom/Fruit:</b> ${esc(p._bloom)}</div><div><b>Prune:</b> ${esc(p._prune)}</div><div><b>Fertilize:</b> ${esc(p._fert)}</div><div><b>Winter:</b> ${esc(p._winter)}</div></div>${p._notes?`<div class="notes">${esc(p._notes)}</div>`:''}<p><button onclick="openModalByIndex(${i})" class="ghost">Edit / Notes</button></p></article>`).join(''); }
function renderCalendar(plants){ $('calendar').innerHTML=MONTHS.map(([short],idx)=>{ const items=plants.filter(p=>monthsFor(p).includes(idx)); return `<div class="month"><div class="month-name">${short}</div><div class="month-track">${items.map(p=>`<span class="pill ${isFruit(p)?'fruit':'bloom'}">${esc(p._name)}</span>`).join('') || '<span class="pill">—</span>'}</div></div>`; }).join(''); }
function monthsFor(p){ const text=`${p._bloom} ${p._fruit}`.toLowerCase(); const found=new Set(); MONTHS.forEach(([short,long],i)=>{ if(text.includes(long)||new RegExp(`\\b${short.toLowerCase()}\\b`).test(text)) found.add(i); }); // Handle seasons and common ranges
 if(/spring/.test(text)){ [2,3,4].forEach(m=>found.add(m)); } if(/summer/.test(text)){ [5,6,7].forEach(m=>found.add(m)); } if(/fall|autumn/.test(text)){ [8,9,10].forEach(m=>found.add(m)); } if(/winter/.test(text)){ [11,0,1].forEach(m=>found.add(m)); }
 // Expand ranges like Jun-July, June to August, Sep-Oct
 const names=MONTHS.map(m=>m[1]); for(let a=0;a<12;a++){ for(let b=0;b<12;b++){ const re=new RegExp(`${names[a].slice(0,3)}[a-z]*\\s*(?:-|to|through|–|—)\\s*${names[b].slice(0,3)}[a-z]*`,'i'); if(re.test(text)){ let x=a; while(true){ found.add(x); if(x===b) break; x=(x+1)%12; if(found.size>12) break; } } } }
 return [...found].sort((a,b)=>a-b); }
function isRabbitTarget(p){ return /high|favorite|candy|very high|ravaged|annihilat/i.test(p._rabbit+' '+p._notes); }
function isRabbitSafe(p){ return /low|resistant|rarely|very low/i.test(p._rabbit+' '+p._notes); }
function isFruit(p){ return /fruit|berry|berries|peach|olive|strawberr|blueberr|basil|mint|oregano|sage|tarragon/i.test(`${p._type} ${p._name} ${p._fruit}`); }
function openModalByIndex(i){ openModal(state.filtered[i]); }
function openModal(p){ $('rowNumber').value=p.rowNumber||p._row||''; $('plantName').value=p._name||''; $('quantity').value=p._qty||''; $('type').value=p._type||''; $('zone').value=p._zone||''; $('sun').value=p._sun||''; $('water').value=p._water||''; $('bloom').value=p._bloom||''; $('rabbit').value=p._rabbit||''; $('prune').value=p._prune||''; $('fertilize').value=p._fert||''; $('fruit').value=p._fruit||''; $('winter').value=p._winter||''; $('notes').value=p._notes||''; $('plantDialog').showModal(); }
async function savePlant(){ const payload={rowNumber:$('rowNumber').value,Plant:$('plantName').value,Quantity:$('quantity').value,Type:$('type').value,Zone:$('zone').value,Sun:$('sun').value,Water:$('water').value,Bloom:$('bloom').value,'Rabbit Risk':$('rabbit').value,Prune:$('prune').value,Fertilize:$('fertilize').value,Fruit:$('fruit').value,Winter:$('winter').value,Notes:$('notes').value}; try{ await fetch(apiUrl({action:'upsert'}),{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify(payload)}); $('plantDialog').close(); $('syncStatus').textContent='Saved. Refreshing…'; setTimeout(loadPlants,1300); }catch(e){ alert('Could not save. Check API_URL and Apps Script deployment permissions.'); } }
function esc(x){ return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])); }
function demoPlants(){ return [{Plant:'Bee Balm',Quantity:3,Type:'Perennial',Sun:'Full sun',Water:'Medium',Bloom:'June-July', 'Rabbit Risk':'Low-Medium', Prune:'Deadhead after bloom', Fertilize:'Light spring feed', Winter:'Dies back; hardy', Notes:'Can mildew in humidity'}, {Plant:'Blueberries',Quantity:2,Type:'Fruit shrub',Sun:'Full sun',Water:'Medium-high',Bloom:'Fruit June-July','Rabbit Risk':'Very high', Prune:'Late winter after year 3', Fertilize:'Acid-loving fertilizer spring', Fruit:'Net before berries turn blue; harvest when fully blue', Winter:'Hardy; protect flowers from late frost'}, {Plant:'Serendipity Allium',Quantity:4,Type:'Perennial',Sun:'Full sun',Water:'Low-medium',Bloom:'Late June-July','Rabbit Risk':'Very low', Prune:'Deadhead or leave seedheads', Fertilize:'Usually none', Winter:'Hardy'}, {Plant:'Swamp Sunflower',Quantity:3,Type:'Perennial',Sun:'Full sun',Water:'Medium-high',Bloom:'Sep-Oct','Rabbit Risk':'Very high', Prune:'Cut down winter', Fertilize:'Light spring feed', Notes:'Rabbits keep eating new growth'}]; }
